---
# tasks file for metricbeat
  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.2-amd64.deb

  - name: install metricbeat deb
    command: sudo dpkg -i metricbeat-7.6.2-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src : {{ path_ansible }}/metricbeat.yml
      dest: {{path_metricbeat_webserver }}/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable system

  - name: setup metricbeat
    command: metricbeat setup

  - name: start metricbeat service
    command: service metricbeat start
